*==============================================================
* ps7_sw_ee.do  --  SW Empirical Exercises 12.1, 12.2, 13.1
*                   ECON UN3412 Problem Set 7 (ungraded recitation)
*--------------------------------------------------------------
* This file mirrors the TA's recitation 11 do-file (rec11.do):
*   - ivregress ... , small r  (small-sample SE adjustment)
*   - lincom for the 6/-2/-1 predicted change with delta-method SE
*   - test attend_v attend_m attend_n  (joint zero, as in rec11)
*   - Sargan-Hansen J via NR^2 from residual regression
*   - LPM interaction regressions for Q3(b),(c)
* Supplementary: we also compute disaggregated callback rates and
* a balance F-test for Q3(d), which rec11 did not cover.
*
* Produces output/tables/prob_sw_ee_macros.tex with auto-generated
* \newcommand macros for the writeup.
*==============================================================

clear all
set more off
capture log close
* Resolve the project root portably: allow launch from homework_07/ or do_files/.
capture confirm file "data/fertility.dta"
if _rc {
    capture confirm file "../data/fertility.dta"
    if _rc {
        di as err "Could not find data/fertility.dta. Run from homework_07 or homework_07/do_files."
        exit 601
    }
    cd ..
}
capture mkdir "output"
capture mkdir "output/tables"
log using "do_files/ps7_sw_ee.log", replace text

file open mac using "output/tables/prob_sw_ee_macros.tex", write replace
file write mac "% Auto-generated by ps7_sw_ee.do; do not edit by hand." _n

*==============================================================
* E12.1  Fertility and labor supply  (fertility.dta)
*==============================================================
use "data/fertility.dta", clear
di _dup(60) "=" _n "E12.1 FERTILITY" _n _dup(60) "="
count
scalar n_fert = r(N)

* (a) OLS of weeksm1 on morekids
reg weeksm1 morekids, r
scalar ff_a_b  = _b[morekids]
scalar ff_a_se = _se[morekids]

* (c) First stage: morekids on samesex
reg morekids samesex, r
scalar ff_c_b  = _b[samesex]
scalar ff_c_se = _se[samesex]
test samesex
scalar ff_c_F  = r(F)

* (f) IV: weeksm1 on morekids, instrument = samesex, no controls  (rec11 style)
ivregress 2sls weeksm1 (morekids = samesex), small r
scalar ff_f_b  = _b[morekids]
scalar ff_f_se = _se[morekids]
estat firststage

* (g) IV with exogenous controls agem1 black hispan othrace  (rec11 style)
ivregress 2sls weeksm1 (morekids = samesex) agem1 black hispan othrace, small r
scalar ff_g_b  = _b[morekids]
scalar ff_g_se = _se[morekids]
estat firststage
* First-stage F for samesex with controls (for macro display)
reg morekids samesex agem1 black hispan othrace, r
test samesex
scalar ff_g_F  = r(F)

file write mac "\newcommand{\fertN}{"       %9.0fc (n_fert)  "}" _n
file write mac "\newcommand{\fertOLSb}{"    %7.4f (ff_a_b)   "}" _n
file write mac "\newcommand{\fertOLSse}{"   %7.4f (ff_a_se)  "}" _n
file write mac "\newcommand{\fertFSb}{"     %7.4f (ff_c_b)   "}" _n
file write mac "\newcommand{\fertFSse}{"    %7.4f (ff_c_se)  "}" _n
file write mac "\newcommand{\fertFSF}{"     %6.1f (ff_c_F)   "}" _n
file write mac "\newcommand{\fertIVb}{"     %7.4f (ff_f_b)   "}" _n
file write mac "\newcommand{\fertIVse}{"    %7.4f (ff_f_se)  "}" _n
file write mac "\newcommand{\fertIVctrlb}{"  %7.4f (ff_g_b)  "}" _n
file write mac "\newcommand{\fertIVctrlse}{" %7.4f (ff_g_se) "}" _n
file write mac "\newcommand{\fertFSctrlF}{" %6.1f (ff_g_F)   "}" _n

*==============================================================
* E12.2  Movie attendance and assaults (movies.dta)
*==============================================================
use "data/movies.dta", clear
di _dup(60) "=" _n "E12.2 MOVIES" _n _dup(60) "="
count
scalar n_mov = r(N)

gen ln_assaults = ln(assaults)
gen attend = attend_v + attend_m + attend_n

* (a.i) seasonality in ln_assaults
reg ln_assaults month2-month12 year2-year10, r
test month2 month3 month4 month5 month6 month7 month8 month9 month10 month11 month12
scalar mv_ai_F = r(F)
scalar mv_ai_p = r(p)

* (a.ii) seasonality in total attendance
reg attend month2-month12 year2-year10, r
test month2 month3 month4 month5 month6 month7 month8 month9 month10 month11 month12
scalar mv_aii_F = r(F)
scalar mv_aii_p = r(p)

* (b) OLS of ln_assaults on attend_v attend_m attend_n + rec11 controls (w_* h_*)
reg ln_assaults attend_v attend_m attend_n month2-month12 year2-year10 w_* h_*, r
scalar mv_b_bv = _b[attend_v]
scalar mv_b_sev = _se[attend_v]
scalar mv_b_bm = _b[attend_m]
scalar mv_b_sem = _se[attend_m]
scalar mv_b_bn = _b[attend_n]
scalar mv_b_sen = _se[attend_n]

* Pairwise equality tests (for the SW (b)(ii) question as written)
test attend_v = attend_m
scalar mv_b_pvm = r(p)
test attend_v = attend_n
scalar mv_b_pvn = r(p)

* Joint zero test (rec11 style)
test attend_v attend_m attend_n
scalar mv_b_Fj  = r(F)
scalar mv_b_pj  = r(p)

* (b.iii) scenario via lincom (rec11 style): +6M violent, -2M moderate, -1M nonviolent
lincom 6*attend_v - 2*attend_m - 1*attend_n
scalar mv_b_predict = r(estimate)
scalar mv_b_predSE  = r(se)
scalar mv_b_predLo  = r(lb)
scalar mv_b_predHi  = r(ub)

* (c) IV with pr_attend_v/m/n as instruments (rec11 style: small r)
ivregress 2sls ln_assaults (attend_v attend_m attend_n = pr_attend_v pr_attend_m pr_attend_n) month2-month12 year2-year10 w_* h_*, small r
scalar mv_c_bv = _b[attend_v]
scalar mv_c_sev = _se[attend_v]
scalar mv_c_bm = _b[attend_m]
scalar mv_c_sem = _se[attend_m]
scalar mv_c_bn = _b[attend_n]
scalar mv_c_sen = _se[attend_n]
test attend_v = attend_m
scalar mv_c_pvm = r(p)
test attend_v = attend_n
scalar mv_c_pvn = r(p)
lincom 6*attend_v - 2*attend_m - 1*attend_n
scalar mv_c_predict = r(estimate)
scalar mv_c_predSE  = r(se)
scalar mv_c_predLo  = r(lb)
scalar mv_c_predHi  = r(ub)
* First-stage F for each endogenous regressor
reg attend_v pr_attend_v pr_attend_m pr_attend_n month2-month12 year2-year10 w_* h_*, r
test pr_attend_v pr_attend_m pr_attend_n
scalar mv_c_F_v = r(F)
reg attend_m pr_attend_v pr_attend_m pr_attend_n month2-month12 year2-year10 w_* h_*, r
test pr_attend_v pr_attend_m pr_attend_n
scalar mv_c_F_m = r(F)
reg attend_n pr_attend_v pr_attend_m pr_attend_n month2-month12 year2-year10 w_* h_*, r
test pr_attend_v pr_attend_m pr_attend_n
scalar mv_c_F_n = r(F)

* (d) IV with six surrounding-week instruments (rec11 style)
ivregress 2sls ln_assaults (attend_v attend_m attend_n = attend_v_f attend_m_f attend_n_f attend_v_b attend_m_b attend_n_b) month2-month12 year2-year10 w_* h_*, small r
scalar mv_d_bv = _b[attend_v]
scalar mv_d_sev = _se[attend_v]
scalar mv_d_bm = _b[attend_m]
scalar mv_d_sem = _se[attend_m]
scalar mv_d_bn = _b[attend_n]
scalar mv_d_sen = _se[attend_n]
lincom 6*attend_v - 2*attend_m - 1*attend_n
scalar mv_d_predict = r(estimate)
scalar mv_d_predSE  = r(se)

* (e) J-test overidentification, rec11 style: NR^2 from residual regression
ivregress 2sls ln_assaults (attend_v attend_m attend_n = pr_attend_v pr_attend_m pr_attend_n attend_v_f attend_m_f attend_n_f attend_v_b attend_m_b attend_n_b) month2-month12 year2-year10 w_* h_*, small r
predict e_iv, residuals
reg e_iv pr_attend_v pr_attend_m pr_attend_n attend_v_f attend_m_f attend_n_f attend_v_b attend_m_b attend_n_b, r
scalar mv_e_J   = e(r2) * e(N)
scalar mv_e_Jdf = 6    // 9 instruments - 3 endogenous regressors
scalar mv_e_Jp  = 1 - chi2(mv_e_Jdf, mv_e_J)

file write mac "\newcommand{\movN}{"        %4.0f (n_mov)     "}" _n
file write mac "\newcommand{\movAiF}{"      %6.2f (mv_ai_F)   "}" _n
file write mac "\newcommand{\movAip}{"      %6.4f (mv_ai_p)   "}" _n
file write mac "\newcommand{\movAiiF}{"     %6.2f (mv_aii_F)  "}" _n
file write mac "\newcommand{\movAiip}{"     %6.4f (mv_aii_p)  "}" _n
file write mac "\newcommand{\movBbv}{"      %8.5f (mv_b_bv)   "}" _n
file write mac "\newcommand{\movBsev}{"     %8.5f (mv_b_sev)  "}" _n
file write mac "\newcommand{\movBbm}{"      %8.5f (mv_b_bm)   "}" _n
file write mac "\newcommand{\movBsem}{"     %8.5f (mv_b_sem)  "}" _n
file write mac "\newcommand{\movBbn}{"      %8.5f (mv_b_bn)   "}" _n
file write mac "\newcommand{\movBsen}{"     %8.5f (mv_b_sen)  "}" _n
file write mac "\newcommand{\movBpvm}{"     %6.4f (mv_b_pvm)  "}" _n
file write mac "\newcommand{\movBpvn}{"     %6.4f (mv_b_pvn)  "}" _n
file write mac "\newcommand{\movBFj}{"      %6.2f (mv_b_Fj)   "}" _n
file write mac "\newcommand{\movBpj}{"      %6.4f (mv_b_pj)   "}" _n
file write mac "\newcommand{\movBpredict}{" %7.4f (mv_b_predict) "}" _n
file write mac "\newcommand{\movBpredSE}{"  %7.4f (mv_b_predSE)  "}" _n
file write mac "\newcommand{\movBpredLo}{"  %7.4f (mv_b_predLo)  "}" _n
file write mac "\newcommand{\movBpredHi}{"  %7.4f (mv_b_predHi)  "}" _n
file write mac "\newcommand{\movCbv}{"      %8.5f (mv_c_bv)   "}" _n
file write mac "\newcommand{\movCsev}{"     %8.5f (mv_c_sev)  "}" _n
file write mac "\newcommand{\movCbm}{"      %8.5f (mv_c_bm)   "}" _n
file write mac "\newcommand{\movCsem}{"     %8.5f (mv_c_sem)  "}" _n
file write mac "\newcommand{\movCbn}{"      %8.5f (mv_c_bn)   "}" _n
file write mac "\newcommand{\movCsen}{"     %8.5f (mv_c_sen)  "}" _n
file write mac "\newcommand{\movCpvm}{"     %6.4f (mv_c_pvm)  "}" _n
file write mac "\newcommand{\movCpvn}{"     %6.4f (mv_c_pvn)  "}" _n
file write mac "\newcommand{\movCpredict}{" %7.4f (mv_c_predict) "}" _n
file write mac "\newcommand{\movCpredSE}{"  %7.4f (mv_c_predSE)  "}" _n
file write mac "\newcommand{\movCpredLo}{"  %7.4f (mv_c_predLo)  "}" _n
file write mac "\newcommand{\movCpredHi}{"  %7.4f (mv_c_predHi)  "}" _n
file write mac "\newcommand{\movCFv}{"      %6.1f (mv_c_F_v)  "}" _n
file write mac "\newcommand{\movCFm}{"      %6.1f (mv_c_F_m)  "}" _n
file write mac "\newcommand{\movCFn}{"      %6.1f (mv_c_F_n)  "}" _n
file write mac "\newcommand{\movDbv}{"      %8.5f (mv_d_bv)   "}" _n
file write mac "\newcommand{\movDsev}{"     %8.5f (mv_d_sev)  "}" _n
file write mac "\newcommand{\movDbm}{"      %8.5f (mv_d_bm)   "}" _n
file write mac "\newcommand{\movDsem}{"     %8.5f (mv_d_sem)  "}" _n
file write mac "\newcommand{\movDbn}{"      %8.5f (mv_d_bn)   "}" _n
file write mac "\newcommand{\movDsen}{"     %8.5f (mv_d_sen)  "}" _n
file write mac "\newcommand{\movDpredict}{" %7.4f (mv_d_predict) "}" _n
file write mac "\newcommand{\movDpredSE}{"  %7.4f (mv_d_predSE)  "}" _n
file write mac "\newcommand{\movEJ}{"       %6.2f (mv_e_J)    "}" _n
file write mac "\newcommand{\movEJdf}{"     %2.0f (mv_e_Jdf)  "}" _n
file write mac "\newcommand{\movEJp}{"      %6.4f (mv_e_Jp)   "}" _n

*==============================================================
* E13.1  Race/gender discrimination in callbacks  (names.dta)
*==============================================================
use "data/names.dta", clear
di _dup(60) "=" _n "E13.1 NAMES" _n _dup(60) "="
count
scalar n_names = r(N)

gen black_female = black*female
gen black_high   = black*high

* (a) Raw callback rates by race and diff-in-means 95% CI; cross-check with LPM
sum call_back
scalar nm_overall = r(mean)
sum call_back if black == 0
scalar nm_cb_white = r(mean)
scalar nm_n_white  = r(N)
sum call_back if black == 1
scalar nm_cb_black = r(mean)
scalar nm_n_black  = r(N)
scalar nm_diff    = nm_cb_white - nm_cb_black
scalar nm_se_diff = sqrt(nm_cb_white*(1-nm_cb_white)/nm_n_white ///
                        + nm_cb_black*(1-nm_cb_black)/nm_n_black)
scalar nm_t       = nm_diff / nm_se_diff
scalar nm_ci_lo   = nm_diff - 1.96*nm_se_diff
scalar nm_ci_hi   = nm_diff + 1.96*nm_se_diff

* LPM for callback gap (rec11 style)
reg call_back black, r
scalar nm_LPM_b  = _b[black]
scalar nm_LPM_se = _se[black]

* (b) Interaction regression for gender (rec11 style)
reg call_back black female black_female, r
scalar nm_b_black_b   = _b[black]
scalar nm_b_black_se  = _se[black]
scalar nm_b_female_b  = _b[female]
scalar nm_b_female_se = _se[female]
scalar nm_b_bfem_b    = _b[black_female]
scalar nm_b_bfem_se   = _se[black_female]
test black_female
scalar nm_gen_pint    = r(p)
* Implied black effect for men (black=1, female=0): _b[black]
scalar nm_male_b  = nm_b_black_b
scalar nm_male_se = nm_b_black_se
* Implied black effect for women (female=1): _b[black] + _b[black_female]
scalar nm_fem_b   = nm_b_black_b + nm_b_bfem_b
* Compute SE via lincom
lincom black + black_female
scalar nm_fem_se  = r(se)

* (c) High-low difference pooled and by race (rec11 style)
reg call_back high, r
scalar nm_hilo    = _b[high]
scalar nm_hilo_se = _se[high]
reg call_back black high black_high, r
scalar nm_c_black_b    = _b[black]
scalar nm_c_black_se   = _se[black]
scalar nm_c_high_b     = _b[high]
scalar nm_c_high_se    = _se[high]
scalar nm_c_bhigh_b    = _b[black_high]
scalar nm_c_bhigh_se   = _se[black_high]
test black_high
scalar nm_hilo_race_pint = r(p)
* Implied white high-low = _b[high]; implied black high-low = _b[high] + _b[black_high]
scalar nm_wh_hilo = nm_c_high_b
lincom high + black_high
scalar nm_bl_hilo = r(estimate)
* Cell means (for the SW "what is the callback rate for X?" prose)
sum call_back if high == 1 & black == 0
scalar nm_wh_hi = r(mean)
sum call_back if high == 0 & black == 0
scalar nm_wh_lo = r(mean)
sum call_back if high == 1 & black == 1
scalar nm_bl_hi = r(mean)
sum call_back if high == 0 & black == 1
scalar nm_bl_lo = r(mean)

* (d) Balance regression (supplementary; rec11 did not cover this part)
reg black ofjobs yearsexp honors volunteer military empholes ///
    workinschool email computerskills specialskills, r
test ofjobs yearsexp honors volunteer military empholes ///
    workinschool email computerskills specialskills
scalar nm_rand_F = r(F)
scalar nm_rand_p = r(p)

file write mac "\newcommand{\namesN}{"           %5.0f (n_names)    "}" _n
file write mac "\newcommand{\namesCBoverall}{"   %7.4f (nm_overall) "}" _n
file write mac "\newcommand{\namesCBwhite}{"     %7.4f (nm_cb_white) "}" _n
file write mac "\newcommand{\namesCBblack}{"     %7.4f (nm_cb_black) "}" _n
file write mac "\newcommand{\namesNwhite}{"      %5.0f (nm_n_white) "}" _n
file write mac "\newcommand{\namesNblack}{"      %5.0f (nm_n_black) "}" _n
file write mac "\newcommand{\namesDiff}{"        %7.4f (nm_diff)    "}" _n
file write mac "\newcommand{\namesSEdiff}{"      %7.4f (nm_se_diff) "}" _n
file write mac "\newcommand{\namesT}{"           %6.2f (nm_t)       "}" _n
file write mac "\newcommand{\namesCIlo}{"        %7.4f (nm_ci_lo)   "}" _n
file write mac "\newcommand{\namesCIhi}{"        %7.4f (nm_ci_hi)   "}" _n
file write mac "\newcommand{\namesLPMb}{"        %7.4f (nm_LPM_b)   "}" _n
file write mac "\newcommand{\namesLPMse}{"       %7.4f (nm_LPM_se)  "}" _n
file write mac "\newcommand{\namesBblackB}{"     %7.4f (nm_b_black_b)  "}" _n
file write mac "\newcommand{\namesBblackSE}{"    %7.4f (nm_b_black_se) "}" _n
file write mac "\newcommand{\namesBfemB}{"       %7.4f (nm_b_female_b) "}" _n
file write mac "\newcommand{\namesBfemSE}{"      %7.4f (nm_b_female_se) "}" _n
file write mac "\newcommand{\namesBbfemB}{"      %7.4f (nm_b_bfem_b) "}" _n
file write mac "\newcommand{\namesBbfemSE}{"     %7.4f (nm_b_bfem_se) "}" _n
file write mac "\newcommand{\namesMaleb}{"       %7.4f (nm_male_b)  "}" _n
file write mac "\newcommand{\namesMalese}{"      %7.4f (nm_male_se) "}" _n
file write mac "\newcommand{\namesFemb}{"        %7.4f (nm_fem_b)   "}" _n
file write mac "\newcommand{\namesFemse}{"       %7.4f (nm_fem_se)  "}" _n
file write mac "\newcommand{\namesGenPint}{"     %6.4f (nm_gen_pint) "}" _n
file write mac "\newcommand{\namesHiLo}{"        %7.4f (nm_hilo)    "}" _n
file write mac "\newcommand{\namesHiLose}{"      %7.4f (nm_hilo_se) "}" _n
file write mac "\newcommand{\namesCblackB}{"     %7.4f (nm_c_black_b) "}" _n
file write mac "\newcommand{\namesCblackSE}{"    %7.4f (nm_c_black_se) "}" _n
file write mac "\newcommand{\namesChighB}{"      %7.4f (nm_c_high_b) "}" _n
file write mac "\newcommand{\namesChighSE}{"     %7.4f (nm_c_high_se) "}" _n
file write mac "\newcommand{\namesCbhighB}{"     %7.4f (nm_c_bhigh_b) "}" _n
file write mac "\newcommand{\namesCbhighSE}{"    %7.4f (nm_c_bhigh_se) "}" _n
file write mac "\newcommand{\namesWhHi}{"        %7.4f (nm_wh_hi)   "}" _n
file write mac "\newcommand{\namesWhLo}{"        %7.4f (nm_wh_lo)   "}" _n
file write mac "\newcommand{\namesWhHiLo}{"      %7.4f (nm_wh_hilo) "}" _n
file write mac "\newcommand{\namesBlHi}{"        %7.4f (nm_bl_hi)   "}" _n
file write mac "\newcommand{\namesBlLo}{"        %7.4f (nm_bl_lo)   "}" _n
file write mac "\newcommand{\namesBlHiLo}{"      %7.4f (nm_bl_hilo) "}" _n
file write mac "\newcommand{\namesHiLoRacePint}{" %6.4f (nm_hilo_race_pint) "}" _n
file write mac "\newcommand{\namesRandF}{"       %6.2f (nm_rand_F)  "}" _n
file write mac "\newcommand{\namesRandp}{"       %6.4f (nm_rand_p)  "}" _n

file close mac
log close
